(function(g){var window=this;var j6=function(a){g.cI.call(this,{I:"div",N:"ytp-miniplayer-ui"});this.player=a;this.K=!1;this.J=this.F=this.B=void 0;this.R(a,"minimized",this.ET);this.R(a,"onStateChange",this.dX)},k6=function(a){g.xU.call(this,a);
this.o=new j6(this.player);this.o.hide();g.lU(this.player,this.o.element,4);a.app.J.o&&(this.load(),g.U(a.getRootNode(),"ytp-player-minimized",!0))};
g.t(j6,g.cI);g.h=j6.prototype;
g.h.show=function(){this.B=new g.zu(this.YP,null,this);this.B.start();if(!this.K){this.H=new g.MZ(this.player,this);g.M(this,this.H);g.lU(this.player,this.H.element,4);this.H.F=.6;this.O=new g.iZ(this.player);g.M(this,this.O);this.G=new g.V({I:"div",N:"ytp-miniplayer-scrim"});g.M(this,this.G);this.G.wa(this.element);this.R(this.G.element,"click",this.AE);var a=new g.V({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],T:{"aria-label":"Close"},P:[g.TU()]});g.M(this,a);a.wa(this.G.element);
this.R(a.element,"click",this.UC);this.D=new g.V({I:"div",N:"ytp-miniplayer-controls"});g.M(this,this.D);this.D.wa(this.G.element);this.R(this.D.element,"click",this.AE);var b=new g.V({I:"div",N:"ytp-miniplayer-button-container"});g.M(this,b);b.wa(this.D.element);a=new g.V({I:"div",N:"ytp-miniplayer-play-button-container"});g.M(this,a);a.wa(this.D.element);var c=new g.V({I:"div",N:"ytp-miniplayer-button-container"});g.M(this,c);c.wa(this.D.element);this.M=new g.hY(this.player,this,!1);g.M(this,this.M);
this.M.wa(b.element);b=new g.fY(this.player,this);g.M(this,b);b.wa(a.element);this.L=new g.hY(this.player,this,!0);g.M(this,this.L);this.L.wa(c.element);this.J=new g.WY(this.player,this);g.M(this,this.J);this.J.wa(this.G.element);this.F=new g.iY(this.player,this);g.M(this,this.F);g.lU(this.player,this.F.element,4);this.C=new g.V({I:"div",N:"ytp-miniplayer-buttons"});g.M(this,this.C);g.lU(this.player,this.C.element,4);this.C.hide();a=new g.V({I:"button",ea:["ytp-miniplayer-close-button","ytp-button"],
T:{"aria-label":"Close"},P:[g.TU()]});g.M(this,a);a.wa(this.C.element);this.R(a.element,"click",this.UC);a=new g.V({I:"button",ea:["ytp-miniplayer-replay-button","ytp-button"],T:{"aria-label":"Close"},P:[g.UU()]});g.M(this,a);a.wa(this.C.element);this.R(a.element,"click",this.KU);this.R(this.player,"presentingplayerstatechange",this.ZP);this.R(this.player,"appresize",this.yv);this.R(this.player,"fullscreentoggled",this.yv);this.yv();this.K=!0}0!=this.player.Qh()&&g.cI.prototype.show.call(this);this.F.show();
this.player.Lm("annotations_module")};
g.h.hide=function(){this.B&&(this.B.dispose(),this.B=void 0);g.cI.prototype.hide.call(this);this.player.app.J.o||(this.K&&this.F.hide(),this.player.uk("annotations_module"))};
g.h.X=function(){this.B&&(this.B.dispose(),this.B=void 0);g.cI.prototype.X.call(this)};
g.h.UC=function(){this.player.md();this.player.ya("onCloseMiniplayer")};
g.h.KU=function(){this.player.Yc()};
g.h.AE=function(a){if(a.target==this.G.element||a.target==this.D.element)g.X(this.player).experiments.o("kevlar_miniplayer_scrim_pause")?2==this.player.Qh()?this.player.Yc():this.player.nd():this.player.ya("onExpandMiniplayer")};
g.h.ET=function(){g.U(this.player.getRootNode(),"ytp-player-minimized",this.player.app.J.o);this.player.app.J.o&&0==this.player.Qh()?this.C.show():this.C.hide()};
g.h.YP=function(){g.Oua(this.F);this.J.C();this.B&&this.B.start()};
g.h.ZP=function(a){g.W(a.state,32)&&this.H.hide()};
g.h.yv=function(){var a=this.F,b=g.TT(this.player).Va().width;a.Ga=0;a.F=b;a.H=!1;g.kY(a)};
g.h.dX=function(a){this.player.app.J.o&&(0==a?(this.hide(),this.C.show()):(this.show(),this.C.hide()))};
g.h.Rb=function(){return this.H};
g.h.ld=function(){return!1};
g.h.hk=function(){return!1};
g.h.OF=function(){};
g.h.Fo=function(){};
g.h.Go=function(){};
g.h.Rm=function(){return null};
g.h.vv=function(){return new g.ih(0,0,0,0)};
g.h.xv=function(){};
g.h.tq=function(a,b,c,d,e){a.style.left="";a.style.top="";a.style.bottom="";d=g.Ph(a);var f=g.TT(this.player).Va().width;b&&["ytp-prev-button","ytp-next-button"].some(function(a){return g.Mq(b,a)})?(c=12,a.style.top=12+(e||0)+"px"):(c-=d.width/2,a.style.bottom=25+(e||0)+"px");
a.style.left=g.kd(c,0,f-d.width)+"px"};
g.h.bq=function(){};
g.h.zv=function(){};g.t(k6,g.xU);k6.prototype.init=function(){};
k6.prototype.load=function(){this.player.HC();this.o.show()};
k6.prototype.unload=function(){this.player.JC();this.o.hide()};g.wX.miniplayer=k6;})(_yt_player);
